include		/etc/openldap/schema/core.schema
include		/etc/openldap/schema/cosine.schema
include		/etc/openldap/schema/inetorgperson.schema
include	 	/etc/openldap/schema/misc.schema
include	 	/etc/openldap/schema/nis.schema

modulepath	/usr/lib/openldap
moduleload	back_mdb.so

database config

database	mdb
maxsize		1073741824
suffix		"o=Flintstones"
rootdn		"cn=admin,o=Flintstones"
directory	/var/lib/openldap/openldap-data
index	    objectClass eq

access to attrs=userPassword
    by self write
    by anonymous auth
    by * none

access to dn.base="" by * read
access to * by * read
